### PR TITLE
Improvement upon equipping new item

### PR DESCRIPTION
**Pull request by stefanpavlov**
Equipping new item now updates the character.

### CODE REVIEW

**Comment by ohiohunter** [comment]
This does not work for my barbarian sheet for some reason...am I doing something incrrectly?

**Comment by stefanpavlov** [comment]
What doesn't work? I did some tests with my monk character and with barbarian with the default values and everything seemed to work correctly.

Can you give me your character stats and the two items?

**Comment by ohiohunter** [comment]
Maybe I'm confused as to what everyone else was talking about...When I
choose to equip an item, it does not change anything on my character
sheet...only on  the item comparison page.  I was under the assumption that
when I equipped an item, the character sheet would update with the new
gear...is this not so?

On Thu, Aug 2, 2012 at 9:02 AM, stefanpavlov <
reply@reply.github.com

**Comment by stefanpavlov** [comment]
Oh, you're not confused at all. I had the exact same problem as you - the equip functionality that is implemented here is only working in the item compare page. I expanded it to change your stats on the character sheet too but the change is not yet included in this project.

**Comment by rubensayshi** [comment]
hey mate, sorry that I didn't catch your pull request, somehow github decided to stop mailing me important notifications such as these!?

I'll merge and deploy it right away :-)

**Pull request merged**
