### PR TITLE
Fixed typo in index.html

### PR DESCRIPTION
**Pull request by abl**
Typo in variable reference; causes calculator to not load.

### CODE REVIEW

**Comment by rubensayshi** [comment]
cheers mate, should have never checked in that code without running it :S

**Comment by abl** [comment]
np, do it all the time myself, thanks for putting together this awesome utility!

**Comment by rubensayshi** [comment]
hey mate, I didn't really know how to reach you (I can't find a 'message' feature on github) so I'm just commenting on this so I know you get a message for it ;)

I got a PR here for the newui branch: https://github.com/rubensayshi/d3-ehp-calculator/pull/11
Think you could check it out, it's kinda big so would be nice if some1 other then myself could check it out / test it before I merge it :D

**Comment by abl** [comment]
Man I wish there was some kind of message feature here, just saw this. I'll take a look at it tomorrow morning :)

**Comment by abl** [comment]
oops, too late.

**Comment by rubensayshi** [comment]
haha,

I somehow configured my account to send me e-mails when there are
notifications :D

On Sun, Jun 3, 2012 at 8:58 AM, aleksandyr <
reply@reply.github.com

**Comment by abl** [comment]
auto-filed to my spam folder. Sigh. Gmail.

On Sun, Jun 3, 2012 at 11:17 PM, Ruben de Vries
reply@reply.github.com
wrote:

> haha,
> 
> I somehow configured my account to send me e-mails when there are
> notifications :D
> 
> On Sun, Jun 3, 2012 at 8:58 AM, aleksandyr <
> reply@reply.github.com
> 
> > wrote:
> > 
> > oops, too late.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/rubensayshi/d3-ehp-calculator/pull/4#issuecomment-6083546
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rubensayshi/d3-ehp-calculator/pull/4#issuecomment-6092984

## 

Alexander Lash
alexander.lash@gmail.com
alexander@alum.wpi.edu

**Pull request merged**
