### PR TITLE
Adds WitchDoctor (experimental)

### PR DESCRIPTION
**Pull request by MrMarvin**
I had a fun time adding the WitchDoctor to this tool, never touched Backbone.js before.
However, this was done during my lunch break and should not yet be considered "production" ready. Im looking forward to verify the numbers with the game as soon as I log in the next time.

Just wanted to make sure you see this asap so the work isn't done twice or something. Feel free to pull whenever your satisfied with the code.

### CODE REVIEW

**Comment by rubensayshi** [comment]
hey, nice going mate! 

Let me know once you've verified that it works corectly and I'll merge it in :-)

I quickly scanned the code and added some notes to a couple of lines

**Comment by rubensayshi** [comment]
Can I merge it :-) ?

**Comment by MrMarvin** [comment]
yep :)

**Comment by rubensayshi** [comment]
hey mate, I didn't really know how to reach you (I can't find a 'message' feature on github) so I'm just commenting on this so I know you get a message for it ;)

I got a PR here for the newui branch: https://github.com/rubensayshi/d3-ehp-calculator/pull/11
Think you could check it out, it's kinda big so would be nice if some1 other then myself could check it out / test it before I merge it :D

**Pull request merged**
