### PR TITLE
Wiz functionality

### PR DESCRIPTION
**Pull request by kdmcclel**
Added multi class support.
Added Wizard skills/runes
 *Blur
 *Glass Cannon
 *Energy Armor
 *Energy Armor - Prismatic
Added display for EHP Melee Only (Wiz Blur)
Default message 'Class Options Not Supported' for DH, Monk, WD
EHP should be fine for DH, Monk, WD just no skills/runes/passives added.

### CODE REVIEW

**Comment by rubensayshi** [comment]
wow, sweet changes made there mate!

hope I can find some time to split the javascript logic for each class across different Models extending a base model today since that would make the code even cleaner <3

**Comment by kdmcclel** [comment]
Yeah that's what I wanted to do, but this was lunch break work.  I think the calculations are off a little bit.  In D3 it's weird the game claims X health per vit but when you do the math its always short from displayed life pool.  Should probably add reduced melee % field and an EHP - Elites for reduced x% damage from elites

**Comment by kdmcclel** [comment]
Or we could write it to pull from the D3 api and have someone enter their battle tag and select their character.

**Comment by rubensayshi** [comment]
Hehe, that would be awesome, hope they hurry up with the API :-)

On Thu, May 24, 2012 at 3:20 PM, kdmcclel <
reply@reply.github.com

**Pull request merged**
